export const conversationTypes = {
  GLOBAL: "CONVERSATION_TYPE.GLOBAL",
  PRIVATE: "CONVERSATION_TYPE.PRIVATE",
};

export const messengerTabNames = {
  CONVERSATIONS: "MESSENGER.TAB_KEY.CONVERSATIONS",
  USERS: "MESSENGER.TAB_KEY.USERS",
};

export const socketTypes = {
  NOTIFICATION: "NOTIFICATION",
  GLOBAL_MSG_INIT: "GLOBAL_MESSAGE_INIT",
  GLOBAL_MSG_SEND: "GLOBAL_MSG_SEND",
  GLOBAL_MSG_RECEIVE: "GLOBAL_MSG_RECEIVE",
  PRIVATE_MSG_INIT: "PRIVATE_MSG_INIT",
  PRIVATE_MSG_SEND: "PRIVATE_MSG_SEND",
  PRIVATE_MSG_RECEIVE: "PRIVATE_MSG_RECEIVE",
  ERROR: "ERROR",
};
